// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:文件ID" json:"id"`                                           // 文件ID
	DomainName string    `gorm:"column:domain_name;not null;comment:域名" json:"domain_name"`                             // 域名
	BizName    string    `gorm:"column:biz_name;not null;comment:业务名称" json:"biz_name"`                                 // 业务名称
	Hash       string    `gorm:"column:hash;not null;comment:文件哈希" json:"hash"`                                         // 文件哈希
	FileSize   int64     `gorm:"column:file_size;not null;comment:文件大小" json:"file_size"`                               // 文件大小
	FileType   string    `gorm:"column:file_type;not null;comment:文件类型" json:"file_type"`                               // 文件类型
	Uploaded   bool      `gorm:"column:uploaded;not null;comment:是否上传" json:"uploaded"`                                 // 是否上传
	IsDeleted  bool      `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
