// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplate = "template"

// Template mapped from table <template>
type Template struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:模板ID" json:"id"`                                           // 模板ID
	Title      string    `gorm:"column:title;not null;comment:标题" json:"title"`                                         // 标题
	Content    string    `gorm:"column:content;not null;comment:内容" json:"content"`                                     // 内容
	IsDeleted  bool      `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Template's table name
func (*Template) TableName() string {
	return TableNameTemplate
}
