// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:账户ID" json:"id"`                                           // 账户ID
	Mobile     string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                                      // 手机号
	Email      string    `gorm:"column:email;not null;comment:电子邮件" json:"email"`                                       // 电子邮件
	Password   string    `gorm:"column:password;not null;comment:密码" json:"password"`                                   // 密码
	Salt       string    `gorm:"column:salt;not null;comment:密码盐" json:"salt"`                                          // 密码盐
	Number     string    `gorm:"column:number;not null;comment:号码" json:"number"`                                       // 号码
	IsDeleted  int32     `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
