// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:视频ID" json:"id"`                        // 视频ID
	UserID       int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                   // 用户ID
	Title        string    `gorm:"column:title;not null;comment:标题" json:"title"`                                         // 标题
	Description  string    `gorm:"column:description;not null;comment:描述" json:"description"`                             // 描述
	VideoURL     string    `gorm:"column:video_url;not null;comment:视频URL" json:"video_url"`                              // 视频URL
	CoverURL     string    `gorm:"column:cover_url;not null;comment:封面URL" json:"cover_url"`                              // 封面URL
	LikeCount    int64     `gorm:"column:like_count;not null;comment:点赞数" json:"like_count"`                              // 点赞数
	CollectCount int64     `gorm:"column:collect_count;not null;comment:收藏数" json:"collect_count"`                        // 收藏数
	ForwardCount int64     `gorm:"column:forward_count;not null;comment:转发数" json:"forward_count"`                        // 转发数
	CommentCount int64     `gorm:"column:comment_count;not null;comment:评论数" json:"comment_count"`                        // 评论数
	IsDeleted    int32     `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
