// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                        // 用户ID
	AccountID       int64     `gorm:"column:account_id;not null;comment:账户ID" json:"account_id"`                             // 账户ID
	Mobile          string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                                      // 手机号
	Email           string    `gorm:"column:email;not null;comment:电子邮件" json:"email"`                                       // 电子邮件
	Name            string    `gorm:"column:name;not null;comment:用户名" json:"name"`                                          // 用户名
	Avatar          string    `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                                       // 头像
	BackgroundImage string    `gorm:"column:background_image;not null;comment:背景图片" json:"background_image"`                 // 背景图片
	Signature       string    `gorm:"column:signature;not null;comment:签名" json:"signature"`                                 // 签名
	IsDeleted       int32     `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime      time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
