// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCollect = "user_collect"

// UserCollect mapped from table <user_collect>
type UserCollect struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id" json:"user_id"`
	BizID        int64     `gorm:"column:biz_id" json:"biz_id"`
	Biz          string    `gorm:"column:biz" json:"biz"`
	CollectionID int64     `gorm:"column:collection_id" json:"collection_id"`
	Status       bool      `gorm:"column:status;not null;comment:0=不收藏 1=收藏" json:"status"`                               // 0=不收藏 1=收藏
	IsDeleted    int32     `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"`                             // 是否删除
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName UserCollect's table name
func (*UserCollect) TableName() string {
	return TableNameUserCollect
}
